general {
    border_size = 2
    no_border_on_floating = false
    gaps_in = 5
    gaps_out = 10
    col.active_border = $color4 $color6 45deg
    col.inactive_border = $background
    layout = dwindle
    resize_on_border = true
    extend_border_grab_area = 15
    hover_icon_on_border = true
}
